# Site settings
author: Ronda Cowen
title: ZsaZsa6
header-img: img/home-bg.png
email: cowenhome5@gmail.com
copyright_name: Ronda Cowen
description: > # this means to ignore newlines until "baseurl:"
  Working towards a better life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ZsaZsa6

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
